### ISSUE TITLE
Migrar data.yaml para data.toml

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/dpm#41]
Usando a sintaxe sugerida em https://github.com/splor-mg/dpm/issues/39#issuecomment-1720270880

**Comment by labanca** [comment]
Até o momento não encontrei uma maneira melhor de criar o ambiente virtual para utlizar tomllib, pois o mesmo tem de ser python 3.11. No git bash do Windows:

```bash
py -3.11 -m venv venv
```

No meu PC usar somente `python -m venv venv` utiliazava o Python 3.9 para criar o ambiente virtual, devido às múltiplas instalações do Python. 

Também não identifiquei ainda porque o Python padrão utilizado para criar venvs era o 3.9 (talvez pela precedência no PATH do Windows).

**Comment by labanca** [comment]
@fjuniorr os containers do docker já estão na versão 3.11 do Python? Se não, isso seria um problema?

Digo isso para os casos como do ploa2024, dentro do qual executamos o `dpm install`.

**Comment by fjuniorr** [comment]
A imagem dos volumes está com a versão 3.11 porque eu [instalei na mão](https://github.com/splor-mg/volumes-docker/blob/main/Dockerfile#L11), mas nos [outros projetos](https://github.com/splor-mg/ppag-planejamento-dados-2024/blob/main/Dockerfile#L5) deve ser tudo a 3.10:

```
root@99f1f92bfbac:/project# python --version
Python 3.10.12
root@99f1f92bfbac:/project# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

Pra eles a instalação é feita de forma mais conveniente via [scripts/install_python.sh](https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_python.sh) e até onde eu entendi a versão instalada não é configurável e usa a [versão default pro Ubuntu 22.04](https://packages.ubuntu.com/search?keywords=python3).

Podemos usar a tomli e usar a sugestão [Building a tomli/tomllib compatibility layer](https://github.com/hukkin/tomli#building-a-tomlitomllib-compatibility-layer) pra declarar a dependência.
