### ISSUE TITLE
Implementar `dpm normalize`

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/dpm#67]
Seguindo na ideia https://github.com/splor-mg/cookiecutter-datapackage/issues/27 um possível comando seria:

```bash
dpm normalize <package> [--output-dir .] [--data-dir data]
```

Para utilizar no cookiecutter seria necessário algo como:

```bash
dpm normalize <package> [--resource resource-name] [--data-dir data]
```

No entanto nesse formato somente é possível gerar os arquivos de dados dos recursos normalizados. Isso significa que seria necessário alguma forma de chamar o comando para produzir somente os metadados a partir dos arquivos de dados normalizados como ocorre hoje com o build.

```bash
dpm normalize <package> [--output-dir .] [--data-dir data] --no-transform
```

**Comment by fjuniorr** [comment]
> No entanto nesse formato somente é possível gerar os arquivos de dados dos recursos normalizados.

Ou podemos simplesmente adicionar uma flag `--metadata-dir` e o arquivo de metadado apropriado (seja um _data package_,  _data resource_, ou _table schema_ controlado com `--type`) seria gerado também. `--no-metadata-dir` não geraria metadados e `--yaml` e `--json` altera o formato de serialização.

**Comment by labanca** [comment]
Ontem enquanto estava criando os parâmetros `--json` e `--yaml` fiquei muito tempo tentando fazer com que esses parametros fossem uma lista de parâmetros, todos vinculados a uma só varíavel parametro, algo como:

```
metadata_format: Annotated[[str], typer.Option("--yaml", "--json")] = "--json",
```

O código acima não funciona. Mas a idéia é que quando o `dpm build` se passar a gerar recursos em vários formatos diferentes (xlsx, txt, csv, etc), uma lista muito extensiva de opções no help talvez fosse inconveniente.
