### ISSUE TITLE
Caminhos relativos errados ao salvar resources na raiz do projeto "../../"

### ISSUE THREAD

**Issue by labanca** [splor-mg/dpm#9]
Ao importar o package DPM e tentar utilizá-lo, as resources estavam sendo salvas dois niveis acima do PWD do projeto:

![image](https://github.com/splor-mg/dpm/assets/7211451/78432b3b-1e3e-4679-a99e-6109cca70b82)

O caminho `../../` é um comando unix para retroceder ao diretório parent duas vezes, o que está fazendo com que os arquivos sejam salvos na raiz do C:/ do Windows.

**Comment by labanca** [comment]
Possível solução:

O DPM ao ser transformado em pacote incluiu os comandos de retroceder diretório na string da variavel dataset dir, conforme imagem a seguir:

![image](https://github.com/splor-mg/dpm/assets/7211451/400b5bd1-5f38-4863-a1a9-0b601f3c3f6a)

Removê-los pode resolver o problema.

**Comment by labanca** [comment]
Mesmo alterando o projeto do DPM origional atualizando no docker e no projeto local testdpm, o erro ainda continua. 

Ao debugar no pycharm o valor da string dataset_dir está correto, mas ao instanciar a variável os caraceters de retroceder para o diretorio parent continuam:

![image](https://github.com/splor-mg/dpm/assets/7211451/e4600a58-02f8-4987-b18f-4314d947274b)


Pode ser um erro devido ao os.path.join estar executando no unix pelo docker.

**Comment by labanca** [comment]
Tentei mudar a string para` /datapackages`, `/datapackages`,` ./datapackages` e nenhuma mudou o comportamento ao salvar os pacotes do dpm. Agora os arquivos não são salvos nem na raiz do C:/

**Comment by fjuniorr** [comment]
@labanca relata aqui qual era o problema e fecha esse issue.

**Comment by labanca** [comment]
Ao que tudo indica, quando o DPM foi transformado em pacote o uso do Twine e outras alterações feitas para prepará-lo para publicação no testepipy resultou nas mudanças dos caminhos relativos de pasta.  Assim o caminho 'datapackages' se tornou '../../datapackages'. 

Mesmo atualizando o pacote no github e no docker não corrigia o erro, pois a versão que estava sendo executada no container do Docker era a que ficava no diretório 'sites-packages' no linux do container . Após identificar isso e remover essa versão, as correções dos caracteres Unix indesejados desapareceram.
